#!/usr/bin/env bash

MASTER_BRANCH="master"
GIT_ROOT="$(git rev-parse --show-toplevel)"

current_branch=$(git rev-parse --abbrev-ref HEAD)
if [[ "$current_branch" != "$MASTER_BRANCH" ]]; then
	exit 0
fi

cd $GIT_ROOT
commit_hash=$(git log --format="%H" -n 1)

if grep '^\.semver$' -q <<< $(git diff-tree --no-commit-id --name-only -r $commit_hash); then
	cd -
	./semver-hook
fi

